### ISSUE TITLE
Wikidata code matching incorrect

### ISSUE THREAD

**Issue by DenisCarriere** [osmlab/wikidata-osm#8]
Going to make a list of these. These codes shouldn't be added manually.

### Kamsar (10.66070,-14.57668) (lat, lng)

![image](https://cloud.githubusercontent.com/assets/550895/20634874/7f20579a-b323-11e6-87a9-b95d6d37d751.png)

http://www.openstreetmap.org/changeset/43188405
http://www.openstreetmap.org/node/321593853

**Comment by planemad** [comment]
@DenisCarriere for edits that came from the Mapbox data team, you can post your list here https://github.com/mapbox/mapping/issues/242

There were a few places during the initial trial that were matched incorrectly because large distance matches were not discarded. This was later re-reviewed and fixed. Please report if you find others.

**Comment by DenisCarriere** [comment]
@planemad Sounds good, I just wanted to approach about this issue you at least once. Overall it's great work, for the amount of thousands of "proper" codes that have been entered, we are bound to have a few slip up, not a big deal in my opinion.

The fact that you created a map that visualizes the offset is great! It's very useful to find Wikidata codes that we incorrectly matched.

Cheers!
